### ISSUE TITLE
Updates to Yosemite?

### ISSUE THREAD

**Issue by Thannah** [schreiberstein/lucidagrandeyosemite#11]
Is it necessary to reinstall your solution after updates to Yosemite, e.g. after installing 10.10.2?

**Comment by schreiberstein** [comment]
No, it should be persistent throughout every (minor) system update.
That is, as long as Apple doesn't change the way to set a certain font to be used as system font (which is, in my opinion, unlikely to happen within a minor system update (e.g. 10.10.0 -> 10.10.1, ...)), it should work.

Best regards,
schreiberstein :apple:

**Comment by Thannah** [comment]
Thank you for your reply!

Best wishes, Nate

**Comment by schreiberstein** [comment]
I just updated my system to 10.10.2 and the patch still works flawlessly.

**Comment by shrx** [comment]
+1, I'm on the latest beta release and didn't have to repatch.

**Comment by schreiberstein** [comment]
@shrx Thanks! I appreciate your feedback! :memo:
