### ISSUE TITLE
Doesn't work on Yosemite 10.10.2

### ISSUE THREAD

**Issue by luizkowalski** [schreiberstein/lucidagrandeyosemite#13]
As title says, the script do not work on Yosemite 10.10.2
Anyone knows why?

*edit*: Yosemite 10.10.2

**Comment by schreiberstein** [comment]
I have not heard about such complaints yet.
Personally, I didn't experience any issues on 10.10.0, 10.10.1 or 10.10.2 (current).

Did you use the latest version of the application?

Best regards,
schreiberstein :apple:

**Comment by luizkowalski** [comment]
Ops, I'm sorry!
I'm using Yosemite 10.10.2 and tried the latest version of application.

**Comment by joshuaiz** [comment]
I'm using lucidagrandeyosemite on 10.10.2 without any issues. Maybe try uninstalling/reinstalling? 

What do you mean "it doesn't work"?

**Comment by luizkowalski** [comment]
Well, maybe I'm doing something wrong
I downloaded the application, unziped e double clicked the file name `Lucida Grande Yosemite` with an automator icon and got the message `The application “Lucida Grande Yosemite” can’t be opened.`

**Comment by schreiberstein** [comment]
Apparently, the file has been corrupted while you were downloading it, as it should have an icon different from Automator.

You could try to download it again.

**Comment by luizkowalski** [comment]
Yes, you are right. Downloaded again and worked!

**Comment by schreiberstein** [comment]
Great to hear! :+1:
