### ISSUE TITLE
El Capitan Update?

### ISSUE THREAD

**Issue by mdl00** [schreiberstein/lucidagrandeyosemite#18]
Something must be different in El Capitan as the font does not get changed. Will you be able to update it? Thanks!

**Comment by vista980622** [comment]
I am the original author of the patch. In short, I am looking at how it can be done, but don't expect anything soon.

While it appears on surface San Francisco has only 9 font weights, there are actually 33 for different display sizes and contexts. A correct mapping between LG font and SF font is required, and since we only have 2 variant of LG font now, the result will not be optimal.

The way El Capitan loads fonts have also changed. This, the typeface, combined with Apple's newly-introduced System Integrity Protection (a.k.a: rootless), there's a lot of work to do.

**Comment by Thannah** [comment]
Just wanted to say that we are all very grateful for all the hard work you guys have done, and ingenuity you applied to this project, right from the beginning up to this date and into the future!

It is wonderful, and all of us who suffered with blurry fonts, eyestrain etc. from the curse of Yosemite are forever grateful to you!

Best wishes, Nate

**Comment by mdl00** [comment]
Thank you very much for responding, vista980622. It's good to hear from the patch creator himself. :stuck_out_tongue_winking_eye: 

That is good to know that an El Capitan-compatible version is in the works!

Obviously, you two are the experts on this, but wouldn't it be possible to map the standard variant of LG to multiple variants of SF?

Also, I have a special request: could you make a patch that would replace the "light" system font with Helvetica Bold? (the reason being that some places that the light font gets used look so much better with a thicker font - thicker than Lucida. See: https://github.com/schreiberstein/lucidagrandeyosemite/issues/10). The Calendar dock icon, prior to Yosemite, used Helvetica Bold.

**Comment by vista980622** [comment]
Thanks, Thannah and mdl00.

It is, in fact, possible to map the standard variant of LG to multiple variants of SF. 
However, it doesn't feel appropriate to map Regular weight of LG to Thin or Ultralight weight of SF (I've tried it, and it looks weird). The way OS X prioritizes loading of system font also changed, from previously loading /Library/Fonts to only loading from /System/Library/Fonts. Writing files to the second folder requires disabling System Integrity Protection, and that can not be done without rebooting into Recovery HD or into Mavericks (SIP is partly in place in Yosemite, so it has to be earlier than that, too).

The way OS X creates font caches and dynamically swaps between SF Text and SF Display also somehow makes the mapping non-perminent. Even with all possible measures are done (including remapping, clearing font caches and *deleting* all traces of San Francisco), Lucida Grande approximately sticks as the system font for three minutes, then El Capitan automatically reverts back to San Francisco.

Also, I'll look into #10 when I have time :)
